--------------------------------------------------------
--  File created - Monday-January-02-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TESTSCENARIOS
--------------------------------------------------------

  CREATE TABLE "ADMIN"."TESTSCENARIOS" 
   (	"TESTSCENARIO" VARCHAR2(40 BYTE), 
	"USERSTORY" VARCHAR2(20 BYTE), 
	"DESCRIPTON" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into ADMIN.TESTSCENARIOS
SET DEFINE OFF;
Insert into ADMIN.TESTSCENARIOS (TESTSCENARIO,USERSTORY,DESCRIPTON) values ('TS01','Story1','Some Description');
Insert into ADMIN.TESTSCENARIOS (TESTSCENARIO,USERSTORY,DESCRIPTON) values ('TS02','Story1','Some Description');
--------------------------------------------------------
--  DDL for Index TESTSCENARIOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."TESTSCENARIOS_PK" ON "ADMIN"."TESTSCENARIOS" ("TESTSCENARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table TESTSCENARIOS
--------------------------------------------------------

  ALTER TABLE "ADMIN"."TESTSCENARIOS" ADD CONSTRAINT "TESTSCENARIOS_PK" PRIMARY KEY ("TESTSCENARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ADMIN"."TESTSCENARIOS" MODIFY ("TESTSCENARIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table TESTSCENARIOS
--------------------------------------------------------

  ALTER TABLE "ADMIN"."TESTSCENARIOS" ADD FOREIGN KEY ("USERSTORY")
	  REFERENCES "ADMIN"."USERSTORY" ("STORYNUMBER") ENABLE;
