--------------------------------------------------------
--  File created - Monday-January-02-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TESTCASESMANAGEMENT
--------------------------------------------------------

  CREATE TABLE "ADMIN"."TESTCASESMANAGEMENT" 
   (	"TESTCASENAME" VARCHAR2(20 BYTE), 
	"TESTSCENARIO" VARCHAR2(40 BYTE), 
	"DESCRIPTION" VARCHAR2(2000 BYTE), 
	"STEPS" CLOB, 
	"EXPECTEDRESULT" CLOB, 
	"DEVELOPMENTPHASE" VARCHAR2(20 BYTE), 
	"REGRESSION" VARCHAR2(3 BYTE), 
	"AUTOMATION" VARCHAR2(3 BYTE), 
	"CREATEDBY" VARCHAR2(40 BYTE), 
	"ASSIGNEDTO" VARCHAR2(40 BYTE), 
	"ENVIRONMENT" VARCHAR2(20 BYTE), 
	"STATUS" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("STEPS") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("EXPECTEDRESULT") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
REM INSERTING into ADMIN.TESTCASESMANAGEMENT
SET DEFINE OFF;
Insert into ADMIN.TESTCASESMANAGEMENT (TESTCASENAME,TESTSCENARIO,DESCRIPTION,DEVELOPMENTPHASE,REGRESSION,AUTOMATION,CREATEDBY,ASSIGNEDTO,ENVIRONMENT,STATUS) values ('TC01','TS01','Some Description','Sprint1','N','N','White','Bruce','SIT','Pass');
--------------------------------------------------------
--  DDL for Index SYS_C0010670
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."SYS_C0010670" ON "ADMIN"."TESTCASESMANAGEMENT" ("TESTCASENAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table TESTCASESMANAGEMENT
--------------------------------------------------------

  ALTER TABLE "ADMIN"."TESTCASESMANAGEMENT" ADD PRIMARY KEY ("TESTCASENAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TESTCASESMANAGEMENT
--------------------------------------------------------

  ALTER TABLE "ADMIN"."TESTCASESMANAGEMENT" ADD FOREIGN KEY ("TESTSCENARIO")
	  REFERENCES "ADMIN"."TESTSCENARIOS" ("TESTSCENARIO") ENABLE;
