--------------------------------------------------------
--  File created - Monday-January-02-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table USERSTORY
--------------------------------------------------------

  CREATE TABLE "ADMIN"."USERSTORY" 
   (	"STORYNUMBER" VARCHAR2(20 BYTE), 
	"DESCRIPTION" CLOB, 
	"ATTACHMENT" BLOB, 
	"CREATEDBY" VARCHAR2(40 BYTE), 
	"ASSIGNEDTO" VARCHAR2(40 BYTE), 
	"DEVPHASE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("DESCRIPTION") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("ATTACHMENT") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
REM INSERTING into ADMIN.USERSTORY
SET DEFINE OFF;
Insert into ADMIN.USERSTORY (STORYNUMBER,CREATEDBY,ASSIGNEDTO,DEVPHASE) values ('Story1','Me','You','Sprint0');
Insert into ADMIN.USERSTORY (STORYNUMBER,CREATEDBY,ASSIGNEDTO,DEVPHASE) values ('Story2','You','Me','Sprint1');
Insert into ADMIN.USERSTORY (STORYNUMBER,CREATEDBY,ASSIGNEDTO,DEVPHASE) values ('Story3','They','you','Sprint2');
--------------------------------------------------------
--  DDL for Index SYS_C0010666
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."SYS_C0010666" ON "ADMIN"."USERSTORY" ("STORYNUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table USERSTORY
--------------------------------------------------------

  ALTER TABLE "ADMIN"."USERSTORY" ADD PRIMARY KEY ("STORYNUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ADMIN"."USERSTORY" MODIFY ("STORYNUMBER" NOT NULL ENABLE);
